export const emails = [
  {
    id: "1",
    sender: "Sarah Chen",
    senderEmail: "sarah.chen@techcorp.com",
    subject: "Q4 Budget Review Meeting",
    preview: "Hi, I wanted to follow up on our discussion about the Q4 budget allocations...",
    fullContent: "Hi John,\n\nI wanted to follow up on our discussion about the Q4 budget allocations. The finance team has completed their preliminary review and we need to schedule a meeting to go over the findings.\n\nKey points to discuss:\n- Marketing budget increase request\n- Engineering headcount projections\n- Office expansion costs\n\nCould you let me know your availability this week?\n\nBest,\nSarah",
    aiSummary: "Finance team completed Q4 budget review. Meeting needed to discuss marketing budget increase, engineering headcount, and office expansion costs.",
    tasksExtracted: 2,
    tasks: [
      "Schedule Q4 budget review meeting with Sarah Chen",
      "Review marketing budget increase request before meeting"
    ],
    date: "2024-01-15T09:30:00",
    isRead: true,
    priority: "high" as const,
  },
  {
    id: "2",
    sender: "Michael Ross",
    senderEmail: "m.ross@investors.com",
    subject: "Investor Update Required",
    preview: "The board is requesting an update on the current quarter performance...",
    fullContent: "Dear John,\n\nThe board is requesting an update on the current quarter performance metrics. As discussed in our last call, we need the following:\n\n1. Revenue growth vs projections\n2. Customer acquisition costs\n3. Churn rate analysis\n4. Key hires and organizational updates\n\nPlease have this ready by end of week.\n\nRegards,\nMichael",
    aiSummary: "Board requests quarterly performance update including revenue, CAC, churn rate, and organizational updates. Due end of week.",
    tasksExtracted: 1,
    tasks: ["Prepare investor update with Q4 performance metrics by Friday"],
    date: "2024-01-15T08:15:00",
    isRead: false,
    priority: "high" as const,
  },
  {
    id: "3",
    sender: "Lisa Wang",
    senderEmail: "lisa.wang@hr.company.com",
    subject: "New Hire Onboarding Schedule",
    preview: "Please review the onboarding schedule for the three new engineers joining...",
    fullContent: "Hi John,\n\nPlease review the onboarding schedule for the three new engineers joining next Monday. I've attached their backgrounds and the proposed training plan.\n\nWe need your sign-off on:\n- Welcome meeting time slot\n- Team assignment confirmations\n- First week objectives\n\nLet me know if you have any questions.\n\nThanks,\nLisa",
    aiSummary: "Three new engineers starting next Monday. Need approval on welcome meeting, team assignments, and first week objectives.",
    tasksExtracted: 3,
    tasks: [
      "Review onboarding schedule for new engineers",
      "Confirm team assignments",
      "Set first week objectives"
    ],
    date: "2024-01-14T16:45:00",
    isRead: true,
    priority: "medium" as const,
  },
  {
    id: "4",
    sender: "David Kim",
    senderEmail: "david.kim@partners.net",
    subject: "Partnership Proposal Review",
    preview: "Following our conversation at the conference, I've drafted the initial...",
    fullContent: "John,\n\nFollowing our conversation at the conference, I've drafted the initial partnership proposal. This outlines the revenue sharing model and integration timeline we discussed.\n\nI believe this could be a significant opportunity for both companies. Happy to schedule a call to walk through the details.\n\nBest,\nDavid",
    aiSummary: "Partnership proposal drafted following conference discussion. Covers revenue sharing and integration timeline. Call requested to discuss details.",
    tasksExtracted: 1,
    tasks: ["Schedule call with David Kim to review partnership proposal"],
    date: "2024-01-14T14:20:00",
    isRead: true,
    priority: "medium" as const,
  },
  {
    id: "5",
    sender: "Emily Foster",
    senderEmail: "emily.f@marketing.co",
    subject: "Brand Campaign Results",
    preview: "Great news! The Q3 brand campaign exceeded all expectations...",
    fullContent: "Hi John,\n\nGreat news! The Q3 brand campaign exceeded all expectations. Here are the highlights:\n\n- 45% increase in brand awareness\n- 2.5M social media impressions\n- 12% boost in website traffic\n\nI'd love to present these results to the leadership team. Can we find time next week?\n\nExcited to share more details!\nEmily",
    aiSummary: "Q3 brand campaign successful with 45% increase in brand awareness and 2.5M social impressions. Emily wants to present to leadership.",
    tasksExtracted: 1,
    tasks: ["Schedule leadership presentation for Q3 brand campaign results"],
    date: "2024-01-13T11:00:00",
    isRead: true,
    priority: "low" as const,
  },
]

export const tasks = [
  {
    id: "1",
    title: "Prepare investor update with Q4 performance metrics",
    priority: "high" as const,
    status: "pending" as const,
    dueDate: "2024-01-19",
    source: "Email from Michael Ross",
  },
  {
    id: "2",
    title: "Schedule Q4 budget review meeting",
    priority: "high" as const,
    status: "approved" as const,
    dueDate: "2024-01-17",
    source: "Email from Sarah Chen",
  },
  {
    id: "3",
    title: "Review marketing budget increase request",
    priority: "medium" as const,
    status: "pending" as const,
    dueDate: "2024-01-17",
    source: "Email from Sarah Chen",
  },
  {
    id: "4",
    title: "Review onboarding schedule for new engineers",
    priority: "medium" as const,
    status: "completed" as const,
    dueDate: "2024-01-15",
    source: "Email from Lisa Wang",
  },
  {
    id: "5",
    title: "Confirm team assignments for new hires",
    priority: "medium" as const,
    status: "pending" as const,
    dueDate: "2024-01-15",
    source: "Email from Lisa Wang",
  },
  {
    id: "6",
    title: "Schedule call with David Kim - Partnership",
    priority: "medium" as const,
    status: "approved" as const,
    dueDate: "2024-01-18",
    source: "Email from David Kim",
  },
  {
    id: "7",
    title: "Schedule leadership presentation - Brand Campaign",
    priority: "low" as const,
    status: "pending" as const,
    dueDate: "2024-01-22",
    source: "Email from Emily Foster",
  },
  {
    id: "8",
    title: "Set first week objectives for new engineers",
    priority: "low" as const,
    status: "pending" as const,
    dueDate: "2024-01-15",
    source: "Email from Lisa Wang",
  },
]

export const calendarEvents = [
  {
    id: "1",
    title: "Q4 Budget Review",
    date: "2024-01-17",
    time: "10:00 AM",
    duration: "1 hour",
    type: "meeting" as const,
    attendees: ["Sarah Chen", "Finance Team"],
  },
  {
    id: "2",
    title: "Investor Call",
    date: "2024-01-19",
    time: "2:00 PM",
    duration: "30 min",
    type: "meeting" as const,
    attendees: ["Michael Ross", "Board Members"],
  },
  {
    id: "3",
    title: "New Hire Welcome",
    date: "2024-01-22",
    time: "9:00 AM",
    duration: "1 hour",
    type: "meeting" as const,
    attendees: ["Lisa Wang", "New Engineers"],
  },
  {
    id: "4",
    title: "Partnership Discussion",
    date: "2024-01-18",
    time: "3:00 PM",
    duration: "45 min",
    type: "call" as const,
    attendees: ["David Kim"],
  },
  {
    id: "5",
    title: "Brand Campaign Presentation",
    date: "2024-01-23",
    time: "11:00 AM",
    duration: "1 hour",
    type: "meeting" as const,
    attendees: ["Emily Foster", "Leadership Team"],
  },
  {
    id: "6",
    title: "Weekly Team Standup",
    date: "2024-01-15",
    time: "9:30 AM",
    duration: "30 min",
    type: "meeting" as const,
    attendees: ["Direct Reports"],
  },
  {
    id: "7",
    title: "Product Review",
    date: "2024-01-16",
    time: "2:00 PM",
    duration: "2 hours",
    type: "meeting" as const,
    attendees: ["Product Team", "Engineering Leads"],
  },
]

export const aiInsights = [
  {
    id: "1",
    type: "urgent" as const,
    message: "Investor update due in 4 days. 2 data points still pending from finance team.",
    timestamp: "Just now",
  },
  {
    id: "2",
    type: "info" as const,
    message: "AI detected 6 actionable tasks today. 2 require urgent attention.",
    timestamp: "2 hours ago",
  },
  {
    id: "3",
    type: "warning" as const,
    message: "Calendar conflict detected: Two meetings scheduled at 2:00 PM on Thursday.",
    timestamp: "3 hours ago",
  },
  {
    id: "4",
    type: "success" as const,
    message: "Onboarding schedule review task completed. Team assignments confirmed.",
    timestamp: "5 hours ago",
  },
]

export const weeklyStats = {
  emailsProcessed: [42, 38, 55, 49, 61, 45, 52],
  tasksCreated: [8, 12, 15, 10, 14, 9, 11],
  tasksCompleted: [6, 10, 12, 8, 11, 7, 9],
  days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
}

export const tasksByPriority = [
  { priority: "High", count: 2, fill: "var(--color-destructive)" },
  { priority: "Medium", count: 4, fill: "var(--color-warning)" },
  { priority: "Low", count: 2, fill: "var(--color-success)" },
]
